name: Infralovers Container Build

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        baseimage: [standalone-chrome, standalone-firefox]
        baseversion: [4.28]

    uses: infralovers/.github/.github/workflows/container.yml@main
    with:
      dockerfile: Dockerfile
      score: 0
      platforms: "linux/amd64"
      release: true
      image_name: "${{matrix.baseimage}}-behave"
      build_args: |
        SELENIUM_BASE=docker.io/selenium/${{ matrix.baseimage }}:${{ matrix.baseversion }}
